```properties
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5332/sdedev
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.profiles.active=local
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret = ${jwt.secret}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
```



```ini
#server.port=8080
#server.forward-headers-strategy=native
#spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5332/sdedev}
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#spring.profiles.active=local
#jwt.secret = ${jwt.secret}
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
```